# Open visualization
/vis/open VRML2FILE

# Scene
/vis/scene/create
/vis/scene/add/world

# Trajectories
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2

# Axes
/vis/scene/add/axes 0 0 0 50 cm

# Viewer
/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 70 20
/vis/viewer/set/autoRefresh true
/vis/drawVolume
/vis/viewer/flush